hunter_config(Boost VERSION ${HUNTER_Boost_VERSION}
    CMAKE_ARGS 
        BUILD_SHARED_LIBS=ON 
        Boost_USE_STATIC_LIBS=OFF
        Boost_USE_MULTITHREADED=ON
        Boost_USE_STATIC_RUNTIME=OFF
        BOOST_ALL_DYN_LINK=ON
)
